---
title: Exercises
---


# Session 1

## Descriptive Data Assessment

**Task:** Produce an *html_document* with a description of the data set `iris`
including following sections at least:

- About the Data Set (how was the data collected?).
- Variables (meaning of each variable including units when applicable)
- Visualization (Discuss some statistics and graphics including the code to
  produce it).

**Alternative:** You can use an own data set, instead.

**Trained Skills:** 

- Confidence using the `Markdown` language to produce text content.
- Clear report on data source.
- Basic knowledge on statistics.
- Proper use of `R` to produce statistics and graphics.

## Fake Wikipedia Entry

**Task:** Select an article from [Wikipedia](https://en.wikipedia.org/) of your
preference and:

- Copy the text content into an own Rmarkdown document.
- Format the content using `Markdown`.

In this exercise you will attempt to resemble the original article's format as
much as possible (title, sections, sub-sections,   hyperreferences, images
imported from Wikipedia Commons, etc.).

**Trained Skills:**

- Confident use of the language `Markdown`.


# Session 2


## Species Description

**Task:** Select a species of your preference and collect information regarding
its taxonomy, anatomy and some pictures. Produce a document describing this
species, which includes following information:

- Why did you selected this species?
- The code used to create the `taxlist` object with its taxonomy.
- A description of its anatomy, ecology and distribution including some
  pictures.

**Alternatives:** You can describe an organism other than plants.

**Trained Skills:**

- Management of taxonomic lists using `taxlist`.
- Format the content using `Markdown`.

<!--

## Reshaping Tables

- From DB-list to cross table...


# Session 3

## Description of a Taxonomic List

**Task:** Select a Family from the distributed species list and produce the
respective subset and describe it in text mentioning following aspects:

- Source of the taxonomic list
- Name of the selected family
- Number of genera
- Number of species
- A barplot of number of species per genera

In this exercise you should attempt to use in-line code chunks. 

**Alternative:** Use diverse data sets distributed as `taxlist` objects.

**Trained Skills:**

- Management of taxonomic lists using `taxlist`.
- Descriptive statistics applied to taxonomic lists.

## Description of a Set of Vegetation Plots

Subset and description of the whole object.

# Session 4

## Describing Plant Communities

Classification and descriptive Statistics on the basis of environmental
parameters

On the basis of taxonomy

## Pooling Taxa and Plots

Aggregate taxa to the genus rank and compare plots

Aggregate plots to groups and compare 



# Session 5

## Finding Patterns

Ordination assessment and some regression models

## Describing own classifications

Classify by a selected method and describe groups.

-->
